<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Article;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends \Doctrine\ORM\EntityRepository
{

  public function findAllWithArticle(Article $article) {
    return $this->createQueryBuilder("c")
              ->where("c.article = :actual")->setParameter('actual', $article)
              ->getQuery()
              ->getResult();
  }
}
